### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by kevpatts** [badger707/esb-smart-meter-reading-automation#2]
Getting:
```[+] open session ...
[+] calling login page. ..
[+] sending credentials ...
[+] passing AUTH ...
[+] confirm_login:  <Response [200]>
[+] doing some BeautifulSoup ...
Traceback (most recent call last):
  File "/home/kev/readmeter.py", line 109, in <module>
    xoxo = load_smart_meter_stats_v2(esb_user_name, esb_password, meter_mprn)
  File "/home/kev/readmeter.py", line 100, in load_smart_meter_stats_v2
    smart_meter_data = load_esb_data(user, password, mpnr, today_)
  File "/home/kev/readmeter.py", line 58, in load_esb_data
    'client_info': form.find('input', {'name': 'client_info'})['value'],
TypeError: 'NoneType' object is not subscriptable
```

and when I print the output I get:

```html
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
   <head>
      <title>Logging in...</title>
      <meta name='CACHE-CONTROL' content='NO-CACHE'/>
      <meta name='PRAGMA' content='NO-CACHE'/>
      <meta name='EXPIRES' content='-1'/>
   </head>
   <body>
      <form id='auto' method='post' action='https://myaccount.esbnetworks.ie/signin-oidc'>
         <div><input type='hidden' name='error' id='error' value='server_error'/><input type='hidden' name='error_description' id='error_description' value='AADB2C90255: The claims exchange specified in technical profile &#39;SelfAsserted-LocalAccountSignin-Email-MIG&#39; did not complete as expected. You might want to try starting your session over from the beginning.\r\nCorrelation ID: 33d5e233-421c-403f-ac97-5de684e993cf\r\nTimestamp: 2023-10-17 16:40:26Z\r\n'/><input type='hidden' name='state' id='state' value='CfDJ8K-eeNAA6DZKm4MXKzifeEjrXWAWiyPrdWdEHd9ExQx4kCku38yYfBJwGpXjomgpLliQ_pLPMSVpS0509a-7UbyvECvIR1t_sMrGjmxJI7QiUVBVg1hNx5vubGOJRJXHeAV6Ukz7jRZzc2Fu91LIY-K8qfZoyuG49pHmcvcIpQF0Ler7OTTPVJp2yVSgkSy7DolkYD94FOfGYWMmoUTp7R_7DCwx0_yEBWcazT8zhSzsR992XN51bczFuKHTSp7b9jdfibOeXYDo3d5gSp2_Vu8GKT2Gi-wrCJCLB2XisVW5ThT08P_daWHzDPwnqVjZmsdDCiAyDrXw1jX2xLJ7lsulbLOp6Vb0T27CnRA2V7deLzuAjCyx2QTbQWdgYEozSw'/></div>
         <div id='noJavascript' style='visibility: visible; font-family: Verdana'>
            <p>Although we have detected that you have Javascript disabled, you will be able to use the site as normal.</p>
            <p>As part of the authentication process this page may be displayed several times. Please use the continue button below.</p>
            <input type='submit' value='Continue' />
         </div>
         <script type='text/javascript'>\r\n                    <!-- \r\n                        document.getElementById('noJavascript').innerHTML = ''; document.getElementById('auto').submit(); \r\n                    //--></script>
      </form>
   </body>
</html>
```

**Comment by kevpatts** [comment]
I'm an idiot.
